model:
  root: ./models/hub
  weight: 
  name: vit
  pretrained: True # fine-tune
  loss: arcface # arcface
  freeze_layers: all
dataset:
  root: /home/hoangdh/hoangdh/research/image-pretrain/dataset/
  name: celeba_split
hyperparams:
  bs: 128
  lr: 0.0001
  epochs: 5
  optimizer: Adam
  target_size: 224
  image_channels: 3
  scheduler: cosine
  save_freq: 1